# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.ApsiUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='TMP NAME', max_length=60),
            preserve_default=False,
        ),
    ]
