# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20161206_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='state',
            field=models.IntegerField(choices=[(0, 'Rejestracja otwarta'), (1, 'Lista studentdów zaakceptowana')], default=0),
        ),
    ]
