# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 14:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0004_classtype_group_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='time',
            field=models.TimeField(default='02:02:00'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='group',
            name='student_members',
        ),
        migrations.AddField(
            model_name='group',
            name='student_members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
