# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_timeslot_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslot',
            old_name='time',
            new_name='time_end',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='time_start',
            field=models.TimeField(default='02:02:00'),
            preserve_default=False,
        ),
    ]
