# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20161226_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='class_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='courses.ClassType'),
        ),
    ]
