# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20161226_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='max_students_in_group',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeslot',
            name='max_students_enrolled',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
