# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-29 20:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0009_auto_20161226_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='classtype',
            name='groups_state',
            field=models.IntegerField(choices=[(0, 'Rejestracja grup otwarta'), (1, 'Rejestracja grup zamknięta')], default=0),
        ),
        migrations.AddField(
            model_name='group',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default='no-name', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='state',
            field=models.IntegerField(choices=[(0, 'Rejestracja otwarta'), (1, 'Lista studentów zaakceptowana')], default=0),
        ),
        migrations.AlterField(
            model_name='group',
            name='class_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='courses.ClassType'),
        ),
        migrations.AlterField(
            model_name='group',
            name='student_members',
            field=models.ManyToManyField(related_name='attended_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
