# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 07:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20161229_2016'),
        ('courses', '0010_auto_20170103_0703'),
    ]

    operations = [
    ]
