# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_merge_20170103_0712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='max_students_in_group',
        ),
        migrations.AddField(
            model_name='classtype',
            name='max_students_in_group',
            field=models.IntegerField(default=2),
        ),
    ]
