# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20170103_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='classtype',
            name='time_slots_state',
            field=models.IntegerField(choices=[(0, 'Rejestracja na terminy otwarta'), (1, 'Rejestracja na terminy zamknięta')], default=0),
        ),
    ]
