# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-15 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_classtype_time_slots_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtype',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_type', to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='classtype',
            name='max_students_in_group',
            field=models.IntegerField(),
        ),
    ]
